#!/usr/bin/env sh

list=$(find ~/Nextcloud/cheatsheets -name '*.pdf')
input=$(echo "$list" | awk -F "/" '{print $NF}' | sed s/.pdf//g | sort | dmenu -i -p 'Cheat Sheets:')
file=$(echo "$list" | grep $input)

[ -z "$input" ] || zathura $file
