#!/usr/bin/env sh
searches="$HOME/Nextcloud/bookmarks.csv"
browser='brave --new-window'

input=$(cut -f 1 $searches | sed -r '/^\s*$/d' | dmenu -i -p 'Search the web:')
[ -z "$input" ] >/dev/null && exit
	first=$(echo $input | cut -f 1 -d " ")
	second=$(echo $input | cut -f2- -d " ")
	match=$(grep "^$first" $searches)
	regex='[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'

# if no match in the bookmarks list, search with first engine
if [ -z "$match" ]; then
	if [[ $input =~ $regex ]]; then
		url=$input
	else
		# if no search engine
		url=$(head -n 1 $searches | cut -f 2 | sed "s/%s/$input/;")
	fi
	# if only search engine
	elif [ $(echo $input | wc -w) -eq 1 ]; then
		# if in the bookmarks but no search engine
		if [ -z $(echo $match | grep "%s") ]; then
			url=$(echo $match |  cut -f 2 -d " " )
		else
		url=$(echo $match | awk -F "/" '{print $3}')
	fi
else
	url=$(echo $match | cut -f 2 -d " " | sed "s/%s/$second/;")
fi

if [ "$first" == "bb" ]; then
  browser='firefox --new-window'
fi

if [ "$first" == "drop" ]; then
  browser='firefox --new-window'
fi


$browser "$url"
