#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ./Scripts/unicode/ipa | dmenu -i -l 30 -p 'IPA:' | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit
echo "$chosen" | tr -d '\n' | xdotool type --clearmodifiers --file -
