#!/usr/bin/env sh

list=$(find ~/Nextcloud/Literature -name '*.pdf')
input=$(echo "$list" | awk -F "/" '{print $NF}' | sed s/.pdf//g | sort | dmenu -i -p 'Literature:')
file=$(echo "$list" | grep "$input")

[ -z "$input" ] || zathura "$file"
