#!/usr/bin/env sh

cd $HOME/Website &&
hugo --cleanDestinationDir &&
rsync -ruLh --delete --stats --size-only -- \
	$HOME/Website/public/* \
	rawadmin@161.35.25.213:/var/www/alexraw.xyz \
        | tee /tmp/out
notify-send "Website synced!"
$((head -7; tail -0) < /tmp/out)
